# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
workflows:
      version: 2
      test_and_installation:
        jobs:
          - test:
              filters:
                branches:
                  only:
                    - pre-release
jobs:
  test:
    docker:
      - image: circleci/php:7.4.3-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            ## download install
            sudo apt update 
            ## prepare for phpunit
            cd ~/project  && composer install -n --prefer-dist
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Units &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Feature &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
            # installation test
            ##  prepare for  packagist installation test.
            mkdir /tmp/install-test
            cd /tmp/install-test
            composer require takuya/unar-wrapper
            ## 


